version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Password7!
    ports:
      - 5432:5432
    networks:
      - my-budget-store

  api-gateway:
    build: my-bud-api-gateway/src/MyBud.ApiGateway
    ports:
      - 7101:443
      - 5101:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORT: 7101
      ASPNETCORE_URLS: "https://+;http://+"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/Https:/root/.aspnet/https
    networks:
      - my-budget-store

  identity-server-api:
    build: identityserver/src/MyBud.IdentityServer
    ports:
      - 7121:443
      - 5121:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORT: 7121
      ASPNETCORE_URLS: "https://+;http://+"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https:/root/.aspnet/https
    networks:
      - my-budget-store

  products-api:
    build: products-api/src/MyBud.ProductsApi
    ports:
      - 7182:443
      - 5182:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORT: 7182
      ASPNETCORE_URLS: "https://+;http://+"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/Https:/root/.aspnet/https
    networks:
      - my-budget-store

networks:
  my-budget-store:
    external: true
